Deployment log4c - using L&B specific config file.

diff --git a/org.glite.lb.logger/config/startup b/org.glite.lb.logger/config/startup
--- a/org.glite.lb.logger/config/startup
+++ b/org.glite.lb.logger/config/startup
@@ -15,7 +15,7 @@ GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-$GLITE_LOCATION/var}
 LL_PIDFILE=${LL_PIDFILE:-$GLITE_LOCATION_VAR/glite-lb-logd.pid}
 IL_PIDFILE=${IL_PIDFILE:-$GLITE_LOCATION_VAR/glite-lb-interlogd.pid}
 
-unset creds port
+unset creds port log4c
 
 start_daemon()
 {
@@ -31,7 +31,7 @@ start_daemon()
 		rm -f "$pidfile"
 	fi
 	echo -n "Starting $name ..."
-	su - $GLITE_USER -c "$cmd" && echo " done" || echo " FAILED"
+	su - $GLITE_USER -c "$log4c $cmd" && echo " done" || echo " FAILED"
 }
 
 start()
@@ -63,6 +63,14 @@ start()
 	[ -n "$GLITE_LB_LOGGER_PORT" ] && port="--port $GLITE_LB_LOGGER_PORT"
 	[ -n "$GLITE_LB_IL_SOCK" ] && sock="--socket $GLITE_LB_IL_SOCK"
 	[ -n "$GLITE_LB_IL_FPREFIX" ] && fprefix="--file-prefix $GLITE_LB_IL_FPREFIX"
+
+	log4c="$GLITE_LOCATION/etc/glite-lb-log4crc"
+	if test -f "$log4c"; then
+		log4c="LOG4C_RCPATH='$log4c'";
+	else
+		echo "$0: WARNING: config file '$log4c' not found." >&2
+		unset log4c
+	fi
 
 	mkdir -p /var/glite/log 
 	chown $GLITE_USER /var/glite/log
diff --git a/org.glite.lb.server/config/startup b/org.glite.lb.server/config/startup
--- a/org.glite.lb.server/config/startup
+++ b/org.glite.lb.server/config/startup
@@ -26,7 +26,7 @@ GLITE_LB_PROXY_FPREFIX=${GLITE_LB_PROXY_FPREFIX:-'/tmp/glite-lbproxy-ilog_events
 IL_PIDFILE=$GLITE_LOCATION_VAR/glite-lb-interlogd.pid
 NOTIF_IL_PIDFILE=$GLITE_LOCATION_VAR/glite-lb-notif-interlogd.pid
 
-unset creds port
+unset creds port log4c
 
 start_daemon()
 {
@@ -42,7 +42,7 @@ start_daemon()
 		rm -f "$pidfile"
 	fi
 	echo -n "Starting $name ..."
-	su - $GLITE_USER -c "$cmd" && echo " done" || echo " FAILED"
+	su - $GLITE_USER -c "$log4c $cmd" && echo " done" || echo " FAILED"
 }
 
 stop_daemon()
@@ -109,6 +109,14 @@ start()
 			echo "$0: WARNING: /etc/grid-security/hostkey.pem readable by $GLITE_USER"
 			creds="-c /etc/grid-security/hostcert.pem -k /etc/grid-security/hostkey.pem"
 		fi
+	fi
+
+	log4c="$GLITE_LOCATION/etc/glite-lb-log4crc"
+	if test -f "$log4c"; then
+		log4c="LOG4C_RCPATH='$log4c'";
+	else
+		echo "$0: WARNING: config file '$log4c' not found." >&2
+		unset log4c
 	fi
 
 	[ -z "$GLITE_LB_EXPORT_DUMPDIR" ] && GLITE_LB_EXPORT_DUMPDIR=$GLITE_LOCATION_VAR/dump
