Fixed yaim script (proper return code).

diff --git a/org.glite.lb.yaim/config/functions/config_glite_lb.in b/org.glite.lb.yaim/config/functions/config_glite_lb.in
--- a/org.glite.lb.yaim/config/functions/config_glite_lb.in
+++ b/org.glite.lb.yaim/config/functions/config_glite_lb.in
@@ -350,15 +350,15 @@ EOF
   fi
 
   ${GLITE_LB_LOCATION_ETC}/init.d/glite-lb-bkserverd restart
+  if [ ! $? = 0 ] ; then
+    yaimlog ABORT "Service glite-lb-bkserverd failed to start!"
+    return 1
+  fi
+
   if [ x"$GLITE_LB_RTM_ENABLED" = x"true" ]; then
     ${GLITE_LB_LOCATION_ETC}/init.d/glite-lb-harvester restart
   else
     ${GLITE_LB_LOCATION_ETC}/init.d/glite-lb-harvester stop
-  fi
-
-  if [ ! $? = 0 ] ; then
-    yaimlog ABORT "Service glite-lb-bkserverd failed to start!"
-    return 1
   fi
 
   return 0
