merge 1.5

diff --git a/org.glite.lb.server/config/startup b/org.glite.lb.server/config/startup
--- a/org.glite.lb.server/config/startup
+++ b/org.glite.lb.server/config/startup
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
-GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-${GLITE_LOCATION}/var}
+GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-/var/glite}
 
 [ -f /etc/glite.conf ] && . /etc/glite.conf
 [ -f $GLITE_LOCATION/etc/glite-wms.conf ] && . $GLITE_LOCATION/etc/glite-wms.conf
@@ -34,6 +34,13 @@ start()
 		fi
 	fi
 
+	[ -z "$GLITE_LB_EXPORT_DUMPDIR" ] && GLITE_LB_EXPORT_DUMPDIR=/tmp/dump
+	purgedir="--dump-prefix $GLITE_LB_EXPORT_DUMPDIR"
+	[ -d "$GLITE_LB_EXPORT_DUMPDIR" ] || mkdir "$GLITE_LB_EXPORT_DUMPDIR" && chown $GLITE_USER:$GLITE_GROUP "$GLITE_LB_EXPORT_DUMPDIR"
+
+	[ -z "$GLITE_LB_EXPORT_JPREG_MAILDIR" ] && GLITE_LB_EXPORT_JPREG_MAILDIR=/tmp/jpreg
+	maildir="--jpreg-dir $GLITE_LB_EXPORT_JPREG_MAILDIR"
+	[ -d "$GLITE_LB_EXPORT_JPREG_MAILDIR" ] || mkdir "$GLITE_LB_EXPORT_JPREG_MAILDIR" && chown $GLITE_USER:$GLITE_GROUP "$GLITE_LB_EXPORT_JPREG_MAILDIR"
 
 	[ -z "$creds" ] && echo $0: WARNING: No credentials specified. Using default lookup which is dangerous. >&2
 
@@ -43,7 +50,8 @@ start()
 	su - $GLITE_USER -c "$GLITE_LOCATION/bin/glite-lb-bkserverd \
 		--notif-il-sock=/tmp/glite-lb-notif.sock \
 		--notif-il-fprefix=/var/tmp/glite-lb-notif \
-		$creds -i $pidfile $port" && echo " done" || echo " FAILED"
+		$creds -i $pidfile $port $purgedir $maildir" \
+	&& echo " done" || echo " FAILED"
 
 	echo -n Starting glite-lb-notif-interlogd ...
 	su - $GLITE_USER -c "$GLITE_LOCATION/bin/glite-lb-notif-interlogd \
@@ -79,23 +87,29 @@ stop()
 
 status()
 {
+	retval=0
+
 	if netstat -an --unix | grep "^unix .* LISTEN.* /tmp/glite-lb-notif.sock$" >/dev/null 2>&1 ;then
 		echo glite-lb-notif-interlogd running
 	else
 		echo glite-lb-notif-interlogd not running
-		return 1
+		retval=1
 	fi
 
 	if [ -f $pidfile ]; then
 		pid=`cat $pidfile`
 		if ps p $pid >/dev/null 2>&1; then
 			echo glite-lb-bkserverd running as $pid 
-			return 0
+		else
+			echo glite-lb-bkserverd not running
+			retval=1
 		fi
+	else
+		echo glite-lb-bkserverd not running
+		retval=1
 	fi
 
-	echo glite-lb-bkserverd not running
-	return 1
+	return $retval
 }
 
 case x$1 in
