rpmlint fixes

diff --git a/org.glite.lb.harvester/config/startup b/org.glite.lb.harvester/config/startup
--- a/org.glite.lb.harvester/config/startup
+++ b/org.glite.lb.harvester/config/startup
@@ -40,6 +40,7 @@ GLITE_LB_LOCATION_VAR=${GLITE_LB_LOCATION_VAR:-'@glite_var@'}
 
 pidfile=${GLITE_LB_HARVESTER_PIDFILE:-"$GLITE_LB_LOCATION_VAR/glite-lb-harvester.pid"}
 level=${GLITE_LB_HARVESTER_DEBUG_LEVEL:-"1"}
+lockfile=/var/lock/glite-lb-harvester
 
 # database or configuration file needed
 # (using the file as default)
@@ -89,7 +90,14 @@ start_daemon()
 		fi
 	fi
 	echo -n "Starting $name ..."
-	su - $GLITE_USER -c "$log4c $cmd" && echo " done" || echo " FAILED"
+	su - $GLITE_USER -c "$log4c $cmd"
+
+	if [ $? -eq 0 ]; then
+		echo " done"
+		touch $lockfile
+	else
+		echo " FAILED"
+	fi
 }
 
 stop_daemon()
@@ -108,11 +116,13 @@ stop_daemon()
 			if [ $try = 20 ]; then
 				kill -9 $pid
 				echo " force quit after $try retries"
+				rm -f $lockfile
 				return 1
 			fi
 	 	done
 		echo " done"
 		rm -f $pidfile
+		rm -f $lockfile
 	else
 		echo $name not running
 		return 1
diff --git a/org.glite.lb.logger/config/startup b/org.glite.lb.logger/config/startup
--- a/org.glite.lb.logger/config/startup
+++ b/org.glite.lb.logger/config/startup
@@ -42,6 +42,8 @@ LL_PIDFILE=${LL_PIDFILE:-$GLITE_LB_LOCATION_VAR/glite-lb-logd.pid}
 IL_PIDFILE=${IL_PIDFILE:-$GLITE_LB_LOCATION_VAR/glite-lb-interlogd.pid}
 IL_SOCKFILE=/tmp/interlogger.sock
 
+lockfile=/var/lock/glite-lb-locallogger
+
 unset creds port log4c
 
 start_daemon()
@@ -65,7 +67,14 @@ start_daemon()
 		fi
 	fi
 	echo -n "Starting $name ..."
-	su - $GLITE_USER -c "$log4c $cmd" && echo " done" || echo " FAILED"
+	su - $GLITE_USER -c "$log4c $cmd"
+
+	if [ $? -eq 0 ]; then
+		echo " done"
+		touch $lockfile
+	else
+		echo " FAILED"
+	fi
 }
 
 status_daemon()
@@ -171,6 +180,8 @@ stop()
 	if netstat -an --unix | grep "^unix .* LISTEN.* ${GLITE_LB_IL_SOCK:-$IL_SOCKFILE}$" >/dev/null 2>&1 ;then
 		killall -9 glite-lb-interlogd
 	fi
+
+	rm -f $lockfile
 }
 
 status()
diff --git a/org.glite.lb.server/config/startup b/org.glite.lb.server/config/startup
--- a/org.glite.lb.server/config/startup
+++ b/org.glite.lb.server/config/startup
@@ -55,6 +55,8 @@ NOTIF_IL_PIDFILE=$GLITE_LB_LOCATION_VAR/glite-lb-notif-interlogd.pid
 msgconf="$GLITE_LB_LOCATION_ETC/glite-lb/msg.conf"
 [ -f "$msgconf" ] && GLITE_LB_NOTIF_IL_OTHER_OPTIONS="$GLITE_LB_NOTIF_IL_OTHER_OPTIONS -F $msgconf"
 
+lockfile=/var/lock/glite-lb-bkserverd
+
 unset creds port log4c
 
 start_daemon()
@@ -78,7 +80,14 @@ start_daemon()
 		fi
 	fi
 	echo -n "Starting $name ..."
-	su - $GLITE_USER -c "$log4c $cmd" && echo " done" || echo " FAILED"
+	su - $GLITE_USER -c "$log4c $cmd"
+
+	if [ $? -eq 0 ]; then
+		echo " done"
+		touch $lockfile
+	else
+		echo " FAILED"
+	fi
 }
 
 stop_daemon()
@@ -97,10 +106,12 @@ stop_daemon()
 			if [ $try = 20 ]; then
 				kill -9 $pid
 				echo " force quit after $try retries"
+				rm -f $lockfile
 				return 1
 			fi
 	 	done
 		echo " done"
+		rm -f $lockfile
 		rm -f $pidfile
 	else
 		echo $name not running
@@ -156,7 +167,7 @@ start()
 	log4c="LOG4C_RCPATH='$GLITE_LB_LOCATION_ETC/glite-lb'"
 
 	policy="$GLITE_LB_LOCATION_ETC/glite-lb/glite-lb-authz.conf"
-	lcas_log="LCAS_LOG_FILE='/var/log/glite/glite-lb-lcas.log' LCAS_ETC_DIR='$GLITE_LB_LOCATION_ETC/glite-lb'"
+	lcas_log="LCAS_LOG_FILE='/var/log/glite/glite-lb-server-lcas.log' LCAS_ETC_DIR='$GLITE_LB_LOCATION_ETC/glite-lb'"
 	if test -f "$policy"; then
 		# lcas not enabled by default yet
 		policy="--policy '$policy'"
